server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/superhero
    username: dreamhunter
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create